projects = [
    #  { 'name': 'KateTest',         # user-friendly name
    #    'id': '<projectId>',        # string, project id
    #    'userid': '<userEmail>',    # string, email address of the other user who should be assigned tasks in this project
    #    'group': 'self'             #group name
    # },
    { 'name': 'Darius : Bradley',
      'id': '1199889583639765',
      'userid': 'dariuskarel@asana.com',
      'group': 'c&c',
    },
    { 'name': 'Abdul : Bradley',
      'id': '1199672587173252',
      'userid': 'abdulaltair@asana.com',
      'group': 'c&c',
    },
    { 'name': 'Ash : Bradley',
      'id': '1202665355049032',
      'userid': 'ashhart@asana.com',
      'group': 'si',
    },
    { 'name': 'Jack : Bradley',
      'id': '1202665335718602',
      'userid': 'jackflahive@asana.com',
      'group': 'si',
    },
    { 'name': 'Liam : Bradley',
      'id': '1202665335718607',
      'userid': 'liamesliger@asana.com',
      'group': 'si',
    },
    { 'name': 'Matt : Bradley',
      'id': '1202665335718597',
      'userid': 'mattfong@asana.com',
      'group': 'si',
    },
    { 'name': 'Jateen : Bradley',
      'id': '1202678787297916',
      'userid': 'jateenjoshi@asana.com',
      'group': 'si',
    },
    { 'name': 'Chang : Bradley',
      'id': '1202990523927349',
      'userid': 'changxue@asana.com',
      'group': 'si',
    },
    { 'name': 'Harry : Bradley',
      'id': '1202633743228298',
      'userid': 'harryyao@asana.com',
      'group': 'si',
    },
    {
      'name': 'Poom : Bradley',
      'id': '1202983549050247',
      'userid': 'poomchiarawongse@asana.com',
      'group': 'si',
    },
]